#define FPS 60
#define WIDTH 1280
#define HEIGHT 720
#define TEXT_BOX_WIDTH 1280
#define TEXT_BOX_HEIGHT 720
#define FONT_SIZE 16
#define LINE_SPACING (FONT_SIZE)
#define LEFT_PADDING (FONT_SIZE * 2)
#define ROWS (WIDTH/FONT_SIZE)
#define COLS (HEIGHT/FONT_SIZE)
#define MAX_TICK 1

